baseURL: "https://taxfree.dev/"
languageCode: "en-us"
title: "tax_free's blog"
theme: "github-style"

params:
    author: "tax_free"
    github: "taxfree-python"
    twitter: "taxfree_python"
    url: "https://www.taxfree.dev/"
    location: "TokyoTech, Japan"
    favicon: "https://pbs.twimg.com/profile_images/1505012518556561409/g93YcdDs_400x400.jpg"
    avatar: "https://pbs.twimg.com/profile_images/1505012518556561409/g93YcdDs_400x400.jpg"

    params.links:
        title: "link_github"
        href: "https://github.com/taxfree-python"
    params.links:
        title: "link_twitter"
        href: "https://twitter.com/taxfree_python"
        # icon: "https://pbs.twimg.com/profile_images/1505012518556561409/g93YcdDs_400x400.jpg"