baseURL: "https://taxfree-python.github.io/"
languageCode: "en-us"
title: "tax_free's blog"
theme: "github-style"

params:
    author: "tax_free"
    github: "taxfree-python"
    twitter: "taxfree_python"
    url: "https://taxfree-python.github.io/"
    location: "TokyoTech, Japan"
    favicon: "https://pbs.twimg.com/profile_images/1505012518556561409/g93YcdDs_400x400.jpg"

    params.links:
        title: "icon"
        href: "https://twitter.com/taxfree_python"
        icon: "https://github.com/taxfree-python/taxfree-python.github.io/blob/master/static/img/my_icon.png"